### ISSUE TITLE
"Show messages on user input in test.html" mini-project in CONTRIBUTING.md appears to be completed

### ISSUE THREAD

**Issue by kevinb7** [Khan/perseus#21]
I was looking for things to do to get my feet wet with perseus.  In CONTRIBUTING.md there's a list of "mini-projects".  I was going to start with the first once which states:
>Show messages on user input in test.html: In production, there is a message box that shows various clues to the user ("You didn't simplify" or "You used x instead of *"). But those clues don't show up in Perseus for whatever reason. Essentially onClick of the score button or (if the above mini-project is done) the green button, there should be a message that appears. This is becoming more important as these little clues are now going mainstream, with content creators able to add their own custom-tailored hints.

So I made a question to see what the current behaviour was in test.html and it does show a "You didn't simplify ..." message.  Am I misunderstanding this first mini-project or is this done?

![screen shot 2015-02-18 at 10 41 02 am](https://cloud.githubusercontent.com/assets/1044413/6253551/7eab9d4a-b75f-11e4-9a8e-68fa41e63556.png)

**Comment by ariabuckles** [comment]
You're right, that seems to work for "check answer". (sorry, we probably wrote that before "check answer" actually did anything) There's also a "score" button at the top of the page that does grading and outputs the result to the console.

Unfortunately these behave differently right now. "score" highlights empty widgets but doesn't show messages, while "check answer" shows messages but doesn't highlight empty widgets.

If you're looking for a related project, it would be awesome if "check answer" highlighted empty widgets! I'm less worried about "score" not showing the message, since it outputs the result to the console where you can read the message anyways.

**Comment by ariabuckles** [comment]
I'll edit our CONTRIBUTING a bit, too. I think we're no longer really aiming to have small intro projects listed there for this repo given the size and complexity of it.

**Comment by kevinb7** [comment]
I'd still like to do something to help out.  Are the other two mini-projects things that you're interested in having in perseus?  If not, is there someone else I can tackle?  I've been helping out with the live-editor quite a bit and I thought it would be good to contribute to some other projects.

**Comment by ariabuckles** [comment]
I just looked through those two projects, and i don't think they're really valuable right now. I've been meaning to reword that section for a while, you just reminded me.

I'll go look through our bug and new features list and find some smaller things that you might find interesting :). I'm really excited you're looking to contribute! I'm not that great at managing open source contributions right now, but I'm trying to get better.

**Comment by kevinb7** [comment]
Sounds good.  If you create issues on github for some of the bugs/features I can start picking them up.  In the meantime I'm going to try getting an error buddy to show up by the in-line expressions so that I can better acquaint myself with the code.

**Comment by kevinb7** [comment]
CONTRIBUTING.md has been updated.
