### ISSUE TITLE
Are you planning to upgrade Perseus wrt to dependencies?

### ISSUE THREAD

**Issue by tarjei** [Khan/perseus#48]
Hi, I'm just wondering about your plans wrt to further development of Perseus. I see that some of the dependencies are quite old (katex for example) so I'm wondering if you are planning to do something about that in the near future and what (if any) other things you are planning on doing with Perseus. 

Regards,
Tarjei

**Comment by brownhead** [comment]
Hi @tarjei! We usually make upgrades as needed, or when someone feels motivated to go through and do all the testing and support required for an upgrade. If there's a feature or bug fix in particular you'd like to see pulled in, definitely let us know as it'll help motivate an upgrade.

Regarding our higher level plans for Perseus: right now it's a project that is a bit difficult to integrate outside of KA. So our plans for Perseus are motivated by needs coming from within KA (or bug reports coming in through KA trackers). We want this to change such that using Perseus in another project is an awesome experience, and contributing to Perseus isn't a hugely difficult endeavor, but there's a fair amount of complex work and thinking required to do that.

Does this help answer your two questions or do you think I missed my mark?

**Comment by tarjei** [comment]
Thanks, the answer is a great start :)

What I do miss is a small paragraph regarding how to integrate the three main components and what format they expect questions in. Apart from that I'm going to try to piece together an integration soon :)

**Comment by ariabuckles** [comment]
You're right, the documentation (and general useability) for reusing Perseus is lacking. Right now the best way to understand how to use components is probably to look through the source for where they are used, and pass in the same props. This is pretty horrible as far as examples go :(. (Unfortunately, this probably isn't changing anytime soon; I don't think anyone who cares a lot about this has the time to take such a project on currently.)

There are two groups of main components: Editors and Renderers:

Editors:

 * ArticleEditor
 * ItemEditor
 * Editor

Renderers:

 * ArticleRenderer
 * ItemRenderer
 * Renderer

Each *Editor is a component that produces props for the corresponding *Renderer. The specific prop format produced and expected varies slightly.

The most recently written, and therefore simplest, of these is the ArticleEditor/ArticleRenderer. If we look through src/article-renderer.jsx and search for `this.props.`, we find it takes three props: `json`, `apiOptions`, and `enabledFeatures`. `apiOptions` and `enabledFeatures` are "documented" in `src/api-options.jsx` and `src/enabled-features.jsx`. `json` is the main prop that represents the article contents. We will produce such a prop using the ArticleEditor.

The ArticleEditor takes 4 props: `json`--the current article state, `apiOptions`, `enabledFeatures`, and `onChange`, a callback that will be called every time the `json` prop should be changed. You can either use a raw `ArticleEditor` or wrap it in a `StatefulEditorPage componentClass={ArticleEditor}`, which provides an `onChange` prop for you that uses React state of the component.

Both `ArticleEditor` and `StatefulEditorPage componentClass={ArticleEditor}` have a `serialize` method, which you can call to get a json blob representing the current article. This is the prop that should be passed as the `json` prop of `ArticleRenderer`, or may be passed as the `json` prop of an `ArticleEditor` to resume editing of said article in the future.

**Comment by tarjei** [comment]
OK, I've started integrating the ArticleRenderer now, thanks for the input.

I've forked Perseus and am working on a set of PRs for you. 

A couple of questions:
1. Do you think you could get rid of the hubble dependency? It's only used 2 places and is not in NPM. Any strong feelings there?
2. Would you accept a PR to move the ReactComponents dependency to NPM?
3. Would you mind publishing perseus to NPM?

4. Also, what is the "intent" of the 3 different Editor/Render combinations? I.e. what is the difference between them?

Thanks again,
Tarjei

**Comment by tarjei** [comment]
Re hubble again: Maybe another option is to just inline the lib into the src directory or add hubble to npm?

I see that the library has not been changed the last few years.
T

**Comment by ariabuckles** [comment]
I'll answer your questions bullet-by-bullet, but first I think it's worth talking about dependencies in general and what the goals are. Perseus uses npm for all non-KA dependencies (npm's awesome), but for KA-dependencies, using npm means it's harder to modify both the dependency and perseus at the same time, which can make development harder. (npm has `npm link` to sort of work around this issue, but it's global and not version-controlled). The rest of Khan Academy's git repos use submodules for dependencies, and the [KA developer setup](https://github.com/Khan/khan-dotfiles) has git aliases to handle submodules more transparently (otherwise they have their own host of problems). I don't think there's much support for changing that to be npm-based right now.

1. I don't have strong feelings about keeping hubble or not (unfortunately it's not really that well integrated right now, and I do support libraries being used to their fullest or not at all), but if we change it we should be extra careful on testing (which might not be worth it, from my perspective anyways, but I don't spend much time developing in perseus anymore).
2. Probably not, based on the paragraph above (but someone at KA can feel free to chime in and own this if they think that's the right direction to go)
3. Unfortunately Perseus' build system is even messier than react-components'. If it were published to npm, I'd want to ideally make it work nicely with npm so that end-users didn't have to have the exact same webpack configuration. I don't think this it's ready for that until then. Personally, I'd say right now the best way to use it as a dependency would be to either build it and include that file in a dependencies directory, or include building it as part of a custom build step. I'd love for Perseus to have all the quirks that make it difficult to reuse fixed, but it's got a long way to go there.
4. ItemEditor/ItemRenderer are for questions on Khan Academy. They include a question area, [a deprecated answer area], and multiple hints. ArticleEditor/ArticleRenderer are for articles on Khan Academy. They include a list of sections which are rendered next to each other to produce the appearance of the entire article. Editor/Renderer are the base components of perseus which are used to build the editable/renderable area for each part of those (question area, each hint, each section), as well as used internally in perseus to build some other editable parts.
5. I'm not opposed to adding hubble to npm (but really, this is @joelburget's to if he wants that responsibility). Changing perseus to depend on an npm hubble is probably fine based on how little it has changed.

**Comment by tarjei** [comment]
Thanks for a great answer :)

Continuing the debate:

Re points 1 and 5: Maybe the simplest option is just to include hubble into the Perseus source for now.

2. Would it be possible to use a format on the requires that makes it possible to switch between submodules (exporting .jsx) and NPM?

3. Ok. A good start is that it is possible to use react-components and hubble from NPM. Then Perseus can be included as a github dependency instead of going through NPM.

4. Thanks for the clarification! I'm trying to integrate Perseus as a question type in our questions system so I guess I need ItemRenderer then :)
(I'm almost considering aiming directly at the widgets, but I'm not sure how much extra that would give me).

Again, thanks for answering my questions.
Regards,
Tarjei

**Comment by ariabuckles** [comment]
I think I don't fully understand your goals. if you're trying to use perseus as an npm dependency, I think you're going to run into more trouble even if all of its dependencies were from npm. the built perseus-4.js file should support node-style requires though, and I'd recommend just building that and requiring that.

If you want "direct widget access", I'd recommend using `Editor` and `Renderer`. The widget API is a bit compex, and currently nothing outside of those two components re-implements it. If you just want a single widget, you can make a Renderer with the content of `[[☃ grapher 1]]` and appropriate widget options in `widgets:` (you could probably do this for Editor too, and use css to hide the actual editing component if you cared to).

**Comment by joelburget** [comment]
Re hubble: I like it but don't feel the need to upload it to npm. I found it super useful when working on Perseus, bug didn't use it in other places. It's maybe not used in enough places to be worth it, but it's really small.

**Comment by justinj** [comment]
It's also possible to install npm modules via github repos, which might be nicer than a submodule.

**Comment by tarjei** [comment]
@joelburget: Maybe just include Hubble into the source then?

@ariabuckles 
My goal is to use Perseus to create great interactive questions within an existing large ReactJS app.

As a part of that I need to be able to use Perseus as a dependency to that application and I would like to be able to require it using my normal build system, which is based on webpack. I might also want to restrict which widgets I include. Right now I'm hoping to get to a state where I can add Perseus as an npm dependency linked directly to a github repo ( see http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly) and that NPM then installs react-components, kmath and jquery as a dependencies of perseus. I have not fully planned how other Khan librarys will be integrated into the mix - some I might just create doubles of.

T

**Comment by ariabuckles** [comment]
If I were doing that, I'd make a custom build of perseus as a single file that can be included in your project.

How I'd go about this:

 * check out webpack.config.node-perseus.js and make a custom one (with the "commonjs2" libararyTarget, which lets it be required)
 * Modify the global includes in node_modules to use `__non_webpack_require__` (this way you can install react-components as separate dependencies if you want)
 * compile this with webpack
 * copy this source file into your repo and require it.
 * celebrate.

If you wanted to remove certain widgets, I'd just unregister them in your custom build in all-widgets.js.

This isn't super elegant, but there are a lot of steps to get from where we are now to a more elegant place for this.
