### ISSUE TITLE
Cannot use CS Program

### ISSUE THREAD

**Issue by Domiii** [Khan/perseus#53]
When adding a "CS Program" widget, I get the error: `XMLHttpRequest cannot load https://www.khanacademy.org/api/internal/scratchpads/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://khan.github.io' is therefore not allowed access. The response had HTTP status code 404.`

Can I make this work by providing a "Url or Program ID"? And if so how to find said URL or ID?

**Comment by xymostech** [comment]
I think the problem is that the Khan Academy CS programs have access controls so that they don't work on non-KA websites, and khan.github.io isn't allowed access. That widget in particular is very KA-specific, and would have to be modified to be used by someone else.

However, if you have something similar to the CS programs from a different website, you could use the iframe widget to do something similar (the CS program widget mostly just makes it easier to figure out the iframe URL).

Does that answer your question? Feel free to reopen if not. If you're in particular trying to use one of the KA CS programs outside of KA, I'm not sure if that is allowed right now, but would be something else to talk about.
