### ISSUE TITLE
Perseus in npm?

### ISSUE THREAD

**Issue by johngonzalez** [Khan/perseus#57]
This is not a issue, is a question.
Can I find Perseus in npm (node package mananger)?
If answer is yes. How can I find it?
If  answer is not. How can I use Perseus as npm package?

Thanks :)

**Comment by ariabuckles** [comment]
Nope, sorry. The build process especially is just not set up to work with npm right now. If you want to depend on it in a package.json, I'd recommend compiling it with `make build` and putting the resulting `build/perseus-#.js` on your own github somewhere, and depending on that from `require()` or `import`.

**Comment by johngonzalez** [comment]
In my project, is necessary use webpack?
Is sufficient if I include perseus-#.js and perseus-#.css?
What is the difference between perseus-#.js and perseus.js?

**Comment by ariabuckles** [comment]
It's not necessary to use webpack, just using perseus-5.js/perseus-5.css should be fine.

The difference between perseus-#.js and perseus.js is that perseus-#.js has three lines at the top indicating the commit used to build perseus, where perseus.js is the raw built file. Either should work, but perseus-5.js is easier to recreate since it has a commit hash associated with it.

It's probably still necessary to load the Khan/KhanUtil globals; I'd forgotten about that. The relevant files are listed in ke-deps.js, and you can see an example of that being loaded with requirejs in index.html.

This process is a pain, sorry :(.

**Comment by fpereira1** [comment]
I found my way around by just looking at the index.html file on the gh-pages branch, that file loads everything necessary to render perseus I believe.

**Comment by jeremywiebe** [comment]
Closing as Perseus is now [published](https://www.npmjs.com/package/@khanacademy/perseus) on npm.
