### ISSUE TITLE
why do you use make?

### ISSUE THREAD

**Issue by bitterulf** [Khan/perseus#61]
You could use grunt or gulp if you already use node.
Adding more dependencies than needed is a bad design choice.

**Comment by kevinbarabash** [comment]
@bitterulf we use `make` for several different projects because it's a language agnostic build system.  Let me know if you need a hand setting up `make`.

**Comment by ariabuckles** [comment]
I'll chime in since I was the one who chose `make`, even though I don't work for Khan Academy or maintain perseus anymore.

I chose make because:

1. I know `make` really well.
2. I don't know grunt/gulp really well.
3. `make` has stood the test of time, and does what it does (dependencies) very well.
4. `make` is a common tool that's preinstalled or easily installed on most unix platforms. (It requires Xcode command line tools for macs, but these are worth getting regardless.)

I was the one maintaining the build system, so the most important requirements were that it worked and that I could get it to do what I needed. Since the Makefile in perseus was first written, the js-community-favoured build system changed from grunt to gulp, and from concatenation to browserify to webpack.

Perseus is a tool built to render and edit KA's content. `make` let us do that.
