### ISSUE TITLE
Adding some types of widgets clears the question

### ISSUE THREAD

**Issue by JJC1138** [Khan/perseus#71]
As of https://github.com/Khan/perseus/commit/b1a67d6e0db052655be484ed92aafec335448cb5 adding some types of widgets is clearing the question area.

It happens when adding:
Example Graphie Widget, Number Line, Grapher, Interaction, Simulator

It happens when adding the widget using the dropdown, or by pasting in e.g. `[[☃ number-line 1]]` to the question text area.

By putting a breakpoint on `Editor.render()` you can see that the widget does actually get added successfully before the question is cleared.

**Comment by JJC1138** [comment]
Adding one of those problematic widgets causes EditorDemo to re-render, whereas adding other widgets doesn't.

**Comment by JJC1138** [comment]
Adding the widgets actually doesn't clear the question; it sets it back to the value stored in `EditorDemo`'s `props.question`, which is either the empty default or the question passed in to the page via `#content=`

**Comment by JJC1138** [comment]
So (excuse me for showing my ignorance here) I guess the problem is either that those widgets are causing the re-render, or it's that changes to the question aren't getting threaded up to `EditorPage` so that it can re-render without causing any problems? I'd guess the latter?

**Comment by ariabuckles** [comment]
It looks like the main change b1a67d6 makes is rendering with StatefulEditorPage in a component. Looking through https://github.com/Khan/perseus/blob/master/src/stateful-editor-page.jsx , it looks like StatefulEditorPage will "cleanse" any state it has if it gets rerendered with new question/hints props etc. I'd guess that adding any props that represent the question/article to the `_.omit` in there would fix this issue (though I don't know the specific code path that's triggering the top level re-render that wasn't before).

It might make more sense to get rid of that `_.omit` and to only manually feed props through, and to just enumerate all the props that might be relevant to EditorPage and pass them down in StatefulEditorPage.

It also might make sense to have an `initialState` prop or something that can be set/re-set to change the initial state of StatefulEditorPage (similar to how you'd use `initialValue` on a stateful `<input>`), instead of just passing `question` `hints` etc to it on each render.

**Comment by ariabuckles** [comment]
Also: Thanks for finding this :heart:

**Comment by JJC1138** [comment]
Thank you very much for taking a look and for the thorough reply! ❤️

Yep, putting `"question"` and `"hints"` in the `omit` in `componentWillReceiveProps()` does fix it.

I'm a bit of a React beginner I'm afraid and I'm still getting clear on how `StatefulEditorPage` works so I'll let someone else comment on your proposed better fix. :)

As for what changed to trigger the re-rendering: from what I can see, `StatefulEditorPage` has always been re-rendered when adding any widget because its state changes, which seems reasonable to me. But now it has `EditorDemo` above it, and something is making that re-render, but only when adding those specific widgets. I've had a look at the `EditorDemo` code and I can't figure out why that's happening, but perhaps that's irrelevant really.

Thank you again for the reply!

**Comment by samiskin** [comment]
Looks like the seemingly random widgets that cause this problem is due to changing `Khan.scratchpad` which triggers a `forceUpdate` on the `EditorDemo`.  I'd go with swapping the `omit` with `pick` and only selecting the relevant props to `EditorPage`.  I'll ask around to see if that would cause any problems, since I'm not really sure what `StatefulEditorPage`'s `componentWillReceiveProps` call is for (which props could possibly change) in the first place

**Comment by ariabuckles** [comment]
@JJC1138 Yeah, I don't think it's *too* important to figure out why that's rerendering--while that might be worth fixing, the fact that it breaks on a re-render violates the general contract of react-components.

@samiskin the `pick` should be fine, just make sure to capture all the relevant non-content props that could be passed down for an EditorPage. StatefulEditorPage used to also support ArticleEditor's, but it looks like it's not used that way anymore in perseus core (it could be used that way in perseus-one's article editor, but I suspect that would use StatefulArticleEditor too).

**Comment by samiskin** [comment]
@ariabuckles Just as a final check: does 
```js
        this.setState(_(nextProps).pick(
            "apiOptions",
            "enabledFeatures",
            "imageUploader",
            "jsonMode",
        ));
```
look safe to you?  These are the props mentioned in `EditorPage`'s propType declarations / defaults, minus the question data

**Comment by ariabuckles** [comment]
Generally, that `pick` looks good. You'd probably want to revise that prop list a little, but it's most right: jsonMode is changed from EditorPage itself and therefore we shouldn't `pick` it, whereas `developerMode` is constant and we should `pick` it probably (but i can't imagine that actually mattering). `problemNum` is also probably worth picking. I found those just by grepping through `EditorPage`'s code, since its propTypes look incomplete :).

This might be more complicated than I thought because of the [comment here](https://github.com/Khan/perseus/blob/master/src/stateful-editor-page.jsx#L40). If that is still the case (I'd test both perseus one and perseus), you can probably fix it by putting a `key` on the `StatefulEditorPage` render whenever it renders a new problem, since that will trigger an entirely new component (and thus state) if the key ever changes.

**Comment by JJC1138** [comment]
Fixed in https://github.com/Khan/perseus/commit/31ecd5df37aa24bacc7c78526cb996e989ad6a38
Thank you @samiskin! 👍🏻
